[alias]
check-wasm = "check --target wasm32-unknown-unknown --lib --all-features"
clippy-wasm = "clippy --target wasm32-unknown-unknown --lib --all-features"
build-wasm = "build --target wasm32-unknown-unknown --profile wasm-release --lib --all-features"

[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]
