[alias]
check-wasm = "check --target wasm32-wasip1 --lib --all-features"
clippy-wasm = "clippy --target wasm32-wasip1 --lib --all-features"
build-wasm = "build --target wasm32-wasip1 --profile wasm-release --lib --all-features"

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-cpu=generic"]

[target.wasm32-wasi]
rustflags = ["-C", "target-cpu=generic"]

[target.wasm32-wasip1]
rustflags = ["-C", "target-cpu=generic"]

[target.wasm32-wasip2]
rustflags = ["-C", "target-cpu=generic"]
